# Generated by Django 3.0 on 2020-03-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='static/images/article/default.jpg', upload_to='static/images/article'),
        ),
    ]
