# Generated by Django 3.0 on 2020-03-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200330_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_content',
            field=models.TextField(default='such empty...'),
        ),
    ]
